---
apiVersion: v1
kind: Secret
metadata:
    name: ${CNPG_CLUSTER_NAME}-secret
    namespace: ${NAMESPACE}
    labels:
        app: identity-migration
        migration.camunda.io/component: postgresql
type: kubernetes.io/basic-auth
stringData:
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}
---
apiVersion: v1
kind: Secret
metadata:
    name: ${CNPG_CLUSTER_NAME}-superuser-secret
    namespace: ${NAMESPACE}
    labels:
        app: identity-migration
        migration.camunda.io/component: postgresql
type: kubernetes.io/basic-auth
stringData:
    username: root
    password: ${PG_SUPERUSER_PASSWORD}
